// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Styles$ReactTemplate = require("./Styles.bs.js");
var Tracks$ReactTemplate = require("./Tracks.bs.js");
var TrackData$ReactTemplate = require("./TrackData.bs.js");

function str(prim) {
  return prim;
}

function mapUrlToRoute(url) {
  var match = url[/* path */0];
  if (match && match[0] === "new" && !match[1]) {
    return /* NewTracks */1;
  } else {
    return /* Home */0;
  }
}

var component = ReasonReact.reducerComponent("ArcherApp");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var watcherID = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      return Curry._1(self[/* send */3], /* ChangeRoute */[mapUrlToRoute(url)]);
                    }));
              return Curry._1(self[/* onUnmount */4], (function () {
                            return ReasonReact.Router[/* unwatchUrl */2](watcherID);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var match = param[/* state */1][/* route */0];
              return React.createElement("div", {
                          className: Styles$ReactTemplate.pageContainer
                        }, match ? React.createElement("div", undefined, React.createElement("button", {
                                    style: Styles$ReactTemplate.basicButton,
                                    onClick: (function () {
                                        return ReasonReact.Router[/* push */0]("/");
                                      })
                                  }, "Home"), React.createElement("span", undefined, "New Tracks!!!")) : React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Curry.app(TrackData$ReactTemplate.GetTracksQuery[/* make */3], [
                                        undefined,
                                        undefined,
                                        undefined,
                                        undefined,
                                        undefined,
                                        undefined,
                                        undefined,
                                        undefined,
                                        undefined,
                                        (function (param) {
                                            var result = param[/* result */0];
                                            if (typeof result === "number") {
                                              return React.createElement("div", undefined, "Loading");
                                            } else if (result.tag) {
                                              return ReasonReact.element(undefined, undefined, Tracks$ReactTemplate.make(result[0].tracks, /* array */[]));
                                            } else {
                                              return React.createElement("div", undefined, result[0].message);
                                            }
                                          })
                                      ])), React.createElement("div", {
                                    style: Styles$ReactTemplate.newTracksButtonWrapper
                                  }, React.createElement("button", {
                                        style: Styles$ReactTemplate.basicButton,
                                        onClick: (function () {
                                            return ReasonReact.Router[/* push */0]("/new");
                                          })
                                      }, "New Tracks"))));
            }),
          /* initialState */(function () {
              return /* record */[/* route : Home */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.str = str;
exports.mapUrlToRoute = mapUrlToRoute;
exports.component = component;
exports.make = make;
/* component Not a pure module */
