// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Styles$ReactTemplate = require("./Styles.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("Track");

function make(tracks, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var trackItems = $$Array.mapi((function (index, track) {
                      return React.createElement("li", {
                                  id: track.id,
                                  style: Styles$ReactTemplate.trackItem
                                }, React.createElement("div", {
                                      style: Styles$ReactTemplate.flex
                                    }, React.createElement("div", {
                                          style: Styles$ReactTemplate.listItemIndex
                                        }, String(index)), React.createElement("div", undefined, React.createElement("a", {
                                              href: track.url
                                            }, track.name))), React.createElement("div", undefined, React.createElement("img", {
                                          style: Styles$ReactTemplate.listItemCoverArt,
                                          src: track.coverArt
                                        })));
                    }), tracks);
              return React.createElement("ul", {
                          style: Styles$ReactTemplate.trackList
                        }, trackItems);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.str = str;
exports.component = component;
exports.make = make;
/* component Not a pure module */
